repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: fix-byte-order-marker
        stages: ['commit']
      - id: check-case-conflict
        stages: ['commit']
      - id: check-executables-have-shebangs
        stages: ['commit']
      - id: check-shebang-scripts-are-executable
        stages: ['commit']
      - id: check-json
        stages: ['commit']
      - id: pretty-format-json
        stages: ['commit']
      - id: check-xml
        stages: ['commit']
      - id: check-yaml
        stages: ['commit']
        args:
          - "--allow-multiple-documents"
      - id: check-merge-conflict
        stages: ['commit']
      - id: end-of-file-fixer
        exclude: '.*\.idea/.*|robots.iml'
        stages: ['commit']
      - id: trailing-whitespace
        stages: ['commit']
