language: java
sudo: required

jdk:
  - oraclejdk8

#services:
#  - docker

#before_install:
#  - docker pull influxdb:1.0.2-alpine
#  - docker run -d -p 8083:8083 -p 8086:8086 influxdb:1.0.2-alpine
#  - docker ps -a

before_script:
  - pip install pre-commit
  - pre-commit intall

script:
  - pre-commit run --all-files
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
