rootProject.name = "robots"

include("robot-system-lib-parent")
include("robot-system-lib-parent:robot-system-lib-core")
include("robot-system-lib-parent:robot-system-lib-joycon")
include("robot-system-lib-parent:robot-system-lib-raspi")
include("robot-system-lib-parent:robot-system-lib-bouchon")
include("eurobot-system-lib-parent")
include("eurobot-system-lib-parent:eurobot-system-lib-core")
include("eurobot-system-lib-parent:eurobot-system-lib-bouchon")
//include("tinker-parent")
//include("tinker-parent:tinker-robot")
include("nerell-parent")
include("nerell-parent:nerell-common")
include("nerell-parent:nerell-robot")
include("nerell-parent:nerell-utils")
include("nerell-parent:nerell-simulator")
//include("odin-parent")
//include("odin-parent:odin-common")
//include("odin-parent:odin-robot")
//include("odin-parent:odin-utils")
//include("odin-parent:odin-simulator")
include("pami-parent")
include("pami-parent:pami-common")
include("pami-parent:pami-robot")
include("pami-parent:pami-utils")
include("pami-parent:pami-simulator")
