package org.arig.robot.model;

public enum EStatusEvent {
    CALAGE,
    READY,
    START,
    ECHANGE_READY,
    CURRENT_ACTION,

    HAUT_FOND_PRIS,
    ECUEIL_EQUIPE_PRIS,
    ECUEIL_COMMUN_EQUIPE_PRIS,
    ECUEIL_COMMUN_ADVERSE_PRIS,
    MANCHE_AIR_1,
    MANCHE_AIR_2,
    PHARE,
    PAVILLON,
    PORT,
    BOUEE_PRISE,
    DEPOSE_GRAND_PORT,
    DEPOSE_PETIT_PORT,
    STEPS_PETIT_PORT,
    DEPOSE_GRAND_CHENAL_ROUGE,
    DEPOSE_GRAND_CHENAL_VERT,
    DEPOSE_UNITAIRE_GRAND_CHENAL_ROUGE,
    DEPOSE_UNITAIRE_GRAND_CHENAL_VERT,
    DEPOSE_PETIT_CHENAL_ROUGE,
    DEPOSE_PETIT_CHENAL_VERT,

    CONFIG,
    TEAM,
    GIROUETTE,
    HAUT_FOND
}
