package org.arig.robot.model;

public enum StatusEvent {
    CALAGE,
    INIT,
    READY,
    START,
    TEAM,
    STRATEGY,
    CONFIG,
    CURRENT_ACTION,
    CURRENT_POSITION,

    DISTRIBUTEUR_EQUIPE,
    DISTRIBUTEUR_COMMUN_EQUIPE,
    DISTRIBUTEUR_COMMUN_ADVERSE,
    SITE_ECHANTILLON_PRIS,
    SITE_ECHANTILLON_ADVERSE_PRIS,
    SITE_DE_FOUILLE_PRIS,
    SITE_DE_FOUILLE_ADVERSE_PRIS,
    VITRINE_ACTIVE,
    STATUETTE_PRIS,
    STATUETTE_DEPOSE,
    REPLIQUE_DEPOSE,
    ECHANTILLON_ABRI_CHANTIER_DISTRIBUTEUR_PRIS,
    ECHANTILLON_ABRI_CHANTIER_CARRE_FOUILLE_PRIS,
    ECHANTILLON_CAMPEMENT_PRIS,
    SITE_DE_RETOUR,

    BASCULE_CARRE_FOUILLE,
    COULEUR_CARRE_FOUILLE,

    DEPOSE_ABRI_CHANTIER,

    DEPOSE_CAMPEMENT_ROUGE_VERT_NORD,
    DEPOSE_CAMPEMENT_ROUGE_VERT_SUD,
    DEPOSE_CAMPEMENT_BLEU_VERT_NORD,
    DEPOSE_CAMPEMENT_BLEU_VERT_SUD,
    CURRENT_CAMPEMENT,

    DEPOSE_GALERIE_ROUGE,
    DEPOSE_GALERIE_ROUGE_VERT,
    DEPOSE_GALERIE_VERT,
    DEPOSE_GALERIE_BLEU_VERT,
    DEPOSE_GALERIE_BLEU,

    PERIODE_GALERIE
}
