package org.arig.robot.model;

public enum StatusEvent {
    CALAGE,
    INIT,
    READY,
    START,
    TEAM,
    STRATEGY,
    CONFIG,
    CURRENT_ACTION,

    DISTRIBUTEUR_EQUIPE_PRIS,
    DISTRIBUTEUR_COMMUN_EQUIPE_PRIS,
    DISTRIBUTEUR_COMMUN_ADVERSE_PRIS,
    SITE_ECHANTILLON_PRIS,
    SITE_DE_FOUILLE_PRIS,
    VITRINE_ACTIVE,
    STATUETTE_PRIS,
    STATUETTE_DANS_VITRINE,
    REPLIQUE_DEPOSE,
    ECHANTILLON_ABRI_CHANTIER_DISTRIBUTEUR_PRIS,
    ECHANTILLON_ABRI_CHANTIER_CARRE_FOUILLE_PRIS,
    ECHANTILLON_CAMPEMENT_PRIS,
    SITE_DE_RETOUR,

    BASCULE_CARRE_FOUILLE,
    COULEUR_CARRE_FOUILLE,
    DEPOSE_ABRI_CHANTIER,
    DEPOSE_CAMPEMENT_ROUGE,
    DEPOSE_CAMPEMENT_VERT,
    DEPOSE_CAMPEMENT_BLEU,
    DEPOSE_GALERIE_ROUGE,
    DEPOSE_GALERIE_ROUGE_VERT,
    DEPOSE_GALERIE_VERT,
    DEPOSE_GALERIE_VERT_BLEU,
    DEPOSE_GALERIE_BLEU
}
