package org.arig.robot.model.enums;

public enum TypeCalage {
  AVANT,
  ARRIERE,

  FORCE,
  TEMPO,

  PRISE_PRODUIT_PINCE_AVANT,
  PRISE_PRODUIT_SOL_AVANT,
  PRISE_PRODUIT_PINCE_ARRIERE,
  PRISE_PRODUIT_SOL_ARRIERE
}
