---
# Spring properties
spring:
  main:
    web-application-type: NONE

robot:
  # Système d'évittement
  avoidance:
     implementation: SEMI_COMPLETE

  # Config
  pathfinding:
    enable: True
    saveImages: True

  # Monitoring
  monitoring:
    points:
      enable: True

  server:
    port: 9101

# Écran
ecran:
  binary: /home/pi/odin-gui
  socket: /tmp/ecran-odin.sock

# Nerell
nerell:
  socket:
    host: nerell
    port: 9100

# Logging
logging:
  file: ./logs/${execution.id}-traces.log
  pattern:
    file: "%d{ISO8601};%p;%t;%c;%m%n"

---

# Spring properties
spring:
  profiles: monitoring

  main:
    web-application-type: REACTIVE

# Server config
server:
  port: 8081

---

# Spring properties
spring:
  profiles: simulateur

# Écran
ecran:
  binary: /opt/robots-gui

---

# Spring properties
spring:
  profiles: greg

# Nerell
nerell:
  socket:
    host: localhost

---

# Spring properties
spring:
  profiles: damien

# Nerell
nerell:
  socket:
    host: localhost
