---
# Spring properties
spring:
  main:
    web-application-type: NONE

robot:
  # Système d'évittement
  avoidance:
      implementation: SEMI_COMPLETE

  # Config
  pathfinding:
    enable: True
    saveImages: True

  # Monitoring
  monitoring:
    points:
      enable: True

  server:
    port: 9100
    pamis:
      triangle:
        port: 9102
      carre:
        port: 9103
      rond:
        port: 9104

# Écran
ecran:
  binary: /home/pi/robots-gui
  socket: /tmp/ecran-nerell.sock

# PAMIs
pamis:
  triangle:
    socket:
      host: pami-triangle
      port: 9202
  carre:
    socket:
      host: pami-carre
      port: 9203
  rond:
    socket:
      host: pami-rond
      port: 9204

# Balise de vision
balise:
  socket:
    host: overlord
    port: 50667

# Logging
logging:
  file:
    name: ./logs/${execution.id}-traces.log
  pattern:
    file: "%d{ISO8601};%p;%t;%c;%m%n"

---

# Spring properties
spring:
  config:
    activate:
      on-profile: monitoring

  main:
    web-application-type: REACTIVE

# Server config
server:
  port: 8080

---

# Spring properties
spring:
  config:
    activate:
      on-profile: simulateur

# Écran
ecran:
  binary: /opt/robots-gui

# Balise de vision
balise:
  impl: BOUCHON

---

# Spring properties
spring:
  config:
    activate:
      on-profile: greg

# Balise de vision
balise:
  impl: SOCKET
  socket:
    host: localhost

# PAMIs
pamis:
  triangle:
    socket:
      host: localhost
  carre:
    socket:
      host: localhost
  rond:
    socket:
      host: localhost

---

# Spring properties
spring:
  config:
    activate:
      on-profile: greg-mac

# Écran
ecran:
  binary: ${user.home}/sogelink/workspaces/arig-workspaces/cpp-linux/build-robots-gui-Desktop_Qt_5_15_2_clang_64bit-Debug/robots-gui.app/Contents/MacOS/robots-gui

---

# Spring properties
spring:
  config:
    activate:
      on-profile: damien

# Balise de vision
balise:
  impl: SOCKET
  socket:
    host: sauron

# PAMIs
pamis:
  triangle:
    socket:
      host: localhost
  carre:
    socket:
      host: localhost
  rond:
    socket:
      host: localhost

# Ecran
ecran:
  binary: /home/damiensorel@sglk.local/arig/cpp-linux/build-robots-gui-Desktop-Debug/robots-gui

---

# Spring properties
spring:
  config:
    activate:
      on-profile: eliott

# Balise de vision
balise:
  impl: SOCKET
  socket:
    host: overlord
    port: 50667

# PAMIs
pamis:
  triangle:
    socket:
      host: localhost
  carre:
    socket:
      host: localhost
  rond:
    socket:
      host: localhost

# Ecran
ecran:
  binary: ${user.home}/dev/ARIG/arig-wksp/cpp-linux/robots-gui-build/robots-gui
