---
# Spring properties
spring:
  main:
    web-application-type: NONE

robot:
  ui:
    title: Nerell Robot

  # Système d'évittement
  avoidance:
      implementation: SEMI_FULL

  # Config
  pathfinding:
    enable: True
    saveImages: True

  # Monitoring
  monitoring:
    points:
      enable: True

# Balise de vision
balise:
  socket:
    host: sauron
    port: 9042

# Logging
logging:
  file: ./logs/${execution.id}-traces.log
  pattern:
    file: "%d{ISO8601};%p;%t;%c;%m%n"

---

# Spring properties
spring:
  profiles: monitoring

  main:
    web-application-type: REACTIVE

# Server config
server:
  port: 8080

---

# Spring properties
spring:
  profiles: simulateur

robot:
  ui:
    title: Nerell Simulateur

balise:
  socket:
    host: localhost
    port: 9042

---

# Spring properties
spring:
  profiles: greg

# Balise de vision
balise:
  socket:
    host: 192.168.1.22

---

# Spring properties
spring:
  profiles: damien

# Balise de vision
balise:
  socket:
    host: 192.168.1.1
