---
# Spring properties
spring:
  main:
    web-application-type: NONE

robot:
  # Système d'évittement
  avoidance:
      implementation: SEMI_COMPLETE

  # Config
  pathfinding:
    enable: True
    saveImages: True

  # Monitoring
  monitoring:
    points:
      enable: True

  server:
    port: 9100

# Écran
ecran:
  binary: /home/pi/nerell-gui
  socket: /tmp/ecran-nerell.sock

# Odin
odin:
  socket:
    host: odin
    port: 9101

# Balise de vision
balise:
  socket:
    host: sauron
    port: 9042

# Logging
logging:
  file: ./logs/${execution.id}-traces.log
  pattern:
    file: "%d{ISO8601};%p;%t;%c;%m%n"

---

# Spring properties
spring:
  profiles: monitoring

  main:
    web-application-type: REACTIVE

# Server config
server:
  port: 8080

---

# Spring properties
spring:
  profiles: simulateur

# Écran
ecran:
  binary: /opt/robots-gui

# Balise de vision
balise:
  impl: BOUCHON

---

# Spring properties
spring:
  profiles: greg

# Balise de vision
balise:
  impl: SOCKET
  socket:
    host: localhost

# Odin
odin:
  socket:
    host: localhost

---

# Spring properties
spring:
  profiles: damien

# Balise de vision
balise:
  socket:
    host: 192.168.1.1

# Odin
odin:
  socket:
    host: localhost
