---
# Spring properties
spring:
  main:
    web-application-type: NONE

robot:
  ui:
    title: Nerell Robot

  # Système d'évittement
  avoidance:
      implementation: FULL # FULL ou BASIC

  # Récupération objet zone adverse
  strategy:
    collectZoneAdverse: False

  # Config
  pathfinding:
    saveImages: True

  # Monitoring
  monitoring:
    points:
      enable: True

---

# Spring properties
spring:
  profiles: monitoring

  main:
    web-application-type: REACTIVE

# Server config
server:
  port: 8080

---

# Spring properties
spring:
  profiles: simulateur

robot:
  ui:
    title: Nerell Simulateur
