---
# Spring properties
spring:
  main:
    web-application-type: NONE

robot:
  ui:
    title: Nerell Robot

  # Configuration des asservissements
  asservissement:
    polaire:
      implementation: DISTANCE_ORIENTATION

  # Système d'évittement
  avoidance:
      implementation: BASIC # FULL ou BASIC

  # Config
  pathfinding:
    saveImages: True

  # Monitoring
  monitoring:
    points:
      enable: True

# Balise de vision
balise:
  socket:
    host: 192.168.1.15
    port: 8080

---

# Spring properties
spring:
  profiles: monitoring

  main:
    web-application-type: REACTIVE

# Server config
server:
  port: 8080

---

# Spring properties
spring:
  profiles: simulateur

robot:
  ui:
    title: Nerell Simulateur
