---
# Spring properties
spring:
  main:
    web-application-type: NONE

robot:
  # Système d'évittement
  avoidance:
     implementation: SEMI_COMPLETE

  # Config
  pathfinding:
    enable: True
    saveImages: True

  # Monitoring
  monitoring:
    points:
      enable: True

nerell:
  socket:
    host: nerell
    #host: 192.168.0.101 # IP de Greg au Gite

# Écran
ecran:
  socket:
    host: overlord
    #host: 192.168.0.101 # IP de Greg au Gite

# Balise de vision
balise:
  socket:
    host: overlord
    port: 50667

# Logging
logging:
  file:
    name: ./logs/${execution.id}-traces.log
  pattern:
    file: "%d{ISO8601};%p;%t;%c;%m%n"

---

# Spring properties
spring:
  config:
    activate:
      on-profile: monitoring

  main:
    web-application-type: REACTIVE

---

# Spring properties
spring:
  config:
    activate:
      on-profile: triangle

# Server config
server:
  port: 8082

# Nerell
nerell:
  socket:
    port: 9102

# Socket server
robot:
  server:
    port: 9202

# Écran
ecran:
  socket:
    port: 8682

---

# Spring properties
spring:
  config:
    activate:
      on-profile: carre

# Server config
server:
  port: 8083

# Nerell
nerell:
  socket:
    port: 9103

# Socket server
robot:
  server:
    port: 9203

# Écran
ecran:
  socket:
    port: 8683

---

# Spring properties
spring:
  config:
    activate:
      on-profile: rond

# Server config
server:
  port: 8084

# Nerell
nerell:
  socket:
    port: 9104

# Socket server
robot:
  server:
    port: 9204

# Écran
ecran:
  socket:
    port: 8684

---

# Spring properties
spring:
  config:
    activate:
      on-profile: simulateur

# Écran
ecran:
  binary: /opt/robots-gui
  socket:
    host: localhost

# Balise de vision
balise:
  impl: BOUCHON

---

# Spring properties
spring:
  config:
    activate:
      on-profile: greg

# Balise de vision
balise:
  impl: SOCKET
  socket:
    host: localhost

# Nerell
nerell:
  socket:
    host: localhost

---

# Spring properties
spring:
  config:
    activate:
      on-profile: greg-mac

ecran:
  binary: ${user.home}/sogelink/workspaces/arig-workspaces/cpp-linux/build-robots-gui-Desktop_Qt_5_15_2_clang_64bit-Debug/robots-gui.app/Contents/MacOS/robots-gui

---

# Spring properties
spring:
  config:
    activate:
      on-profile: damien

# Balise de vision
balise:
  impl: SOCKET
  socket:
    host: sauron

# Nerell
nerell:
  socket:
    host: localhost

# Écran
ecran:
  socket:
    host: localhost
    port: 8686
