---
# Spring properties
spring:
  main:
    web-application-type: NONE

robot:
  # Système d'évittement
  avoidance:
     implementation: SEMI_COMPLETE

  # Config
  pathfinding:
    enable: True
    saveImages: True

  # Monitoring
  monitoring:
    points:
      enable: True

  server:
    port: 9101

# Écran
ecran:
  binary: /home/pi/robots-gui
  socket: /tmp/ecran-odin.sock

# Nerell
nerell:
  socket:
    host: nerell
    port: 9100

# Balise de vision
balise:
  socket:
    host: overlord
    port: 50667

# Logging
logging:
  file:
    name: ./logs/${execution.id}-traces.log
  pattern:
    file: "%d{ISO8601};%p;%t;%c;%m%n"

---

# Spring properties
spring:
  config:
    activate:
      on-profile: monitoring

  main:
    web-application-type: REACTIVE

---

# Spring properties
spring:
  config:
    activate:
      on-profile: triangle

# Server config
server:
  port: 8082

# Écran
ecran:
  socket:
    port: 8681

---

# Spring properties
spring:
  config:
    activate:
      on-profile: carre

# Server config
server:
  port: 8083


# Écran
ecran:
  socket:
    port: 8682

---

# Spring properties
spring:
  config:
    activate:
      on-profile: rond

# Server config
server:
  port: 8084

# Écran
ecran:
  socket:
    port: 8683

---

# Spring properties
spring:
  config:
    activate:
      on-profile: simulateur

# Écran
ecran:
  binary: /opt/robots-gui

# Balise de vision
balise:
  impl: BOUCHON

---

# Spring properties
spring:
  config:
    activate:
      on-profile: greg

# Balise de vision
balise:
  impl: SOCKET
  socket:
    host: localhost

# Nerell
nerell:
  socket:
    host: localhost

# Écran
ecran:
  socket:
    host: localhost
    port: 8686

---

# Spring properties
spring:
  config:
    activate:
      on-profile: greg-mac

---

# Spring properties
spring:
  config:
    activate:
      on-profile: damien

# Balise de vision
balise:
  impl: SOCKET
  socket:
    host: sauron

# Nerell
nerell:
  socket:
    host: localhost

# Écran
ecran:
  socket:
    host: localhost
    port: 8686
