name: build

on:
  push:
    branches:
      - main
  pull_request: { }
  workflow_dispatch: { }

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    needs: pre-commit
    strategy:
      matrix:
        java: [ '21' , '23' ]
    name: Build with Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Build with Gradle
        id: build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_OUTPUT: ${{ secrets.AWS_DEFAULT_OUTPUT }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: ./gradlew build

      - name: Archive production artifacts Java ${{ matrix.java }}
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-report-java${{ matrix.java }}
          path: |
            robot-system-lib-parent/robot-system-lib-core/build/reports/tests/test
            eurobot-system-lib-parent/eurobot-system-lib-core/build/reports/tests/test
          retention-days: 5
